# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Portland"
subtitle: "Oregon"
author:  "AK"
header:
 title: "2005"
 subtitle: "AK"
footer:
 name: "No Insta sorrz"
 bio: "-/-"
social_urls:
  github: "https://github.com/sinnfeinn"
  email: "andreas.kadenbach@gmail.com"


theme: jekyll-theme-slate
